/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerRepoPullsRouteImport } from './routes/$owner.$repo.pulls'
import { Route as OwnerRepoPullNumberRouteImport } from './routes/$owner.$repo.pull.$number'
import { Route as OwnerRepoPullNumberIndexRouteImport } from './routes/$owner.$repo.pull.$number.index'
import { Route as OwnerRepoPullNumberFilesRouteImport } from './routes/$owner.$repo.pull.$number.files'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoPullsRoute = OwnerRepoPullsRouteImport.update({
  id: '/$owner/$repo/pulls',
  path: '/$owner/$repo/pulls',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoPullNumberRoute = OwnerRepoPullNumberRouteImport.update({
  id: '/$owner/$repo/pull/$number',
  path: '/$owner/$repo/pull/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoPullNumberIndexRoute =
  OwnerRepoPullNumberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OwnerRepoPullNumberRoute,
  } as any)
const OwnerRepoPullNumberFilesRoute =
  OwnerRepoPullNumberFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => OwnerRepoPullNumberRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRouteWithChildren
  '/$owner/$repo/pull/$number/files': typeof OwnerRepoPullNumberFilesRoute
  '/$owner/$repo/pull/$number/': typeof OwnerRepoPullNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo/pull/$number/files': typeof OwnerRepoPullNumberFilesRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRouteWithChildren
  '/$owner/$repo/pull/$number/files': typeof OwnerRepoPullNumberFilesRoute
  '/$owner/$repo/pull/$number/': typeof OwnerRepoPullNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/pull/$number'
    | '/$owner/$repo/pull/$number/files'
    | '/$owner/$repo/pull/$number/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/pull/$number/files'
    | '/$owner/$repo/pull/$number'
  id:
    | '__root__'
    | '/'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/pull/$number'
    | '/$owner/$repo/pull/$number/files'
    | '/$owner/$repo/pull/$number/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRepoPullsRoute: typeof OwnerRepoPullsRoute
  OwnerRepoPullNumberRoute: typeof OwnerRepoPullNumberRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pulls': {
      id: '/$owner/$repo/pulls'
      path: '/$owner/$repo/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof OwnerRepoPullsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pull/$number': {
      id: '/$owner/$repo/pull/$number'
      path: '/$owner/$repo/pull/$number'
      fullPath: '/$owner/$repo/pull/$number'
      preLoaderRoute: typeof OwnerRepoPullNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/pull/$number/': {
      id: '/$owner/$repo/pull/$number/'
      path: '/'
      fullPath: '/$owner/$repo/pull/$number/'
      preLoaderRoute: typeof OwnerRepoPullNumberIndexRouteImport
      parentRoute: typeof OwnerRepoPullNumberRoute
    }
    '/$owner/$repo/pull/$number/files': {
      id: '/$owner/$repo/pull/$number/files'
      path: '/files'
      fullPath: '/$owner/$repo/pull/$number/files'
      preLoaderRoute: typeof OwnerRepoPullNumberFilesRouteImport
      parentRoute: typeof OwnerRepoPullNumberRoute
    }
  }
}

interface OwnerRepoPullNumberRouteChildren {
  OwnerRepoPullNumberFilesRoute: typeof OwnerRepoPullNumberFilesRoute
  OwnerRepoPullNumberIndexRoute: typeof OwnerRepoPullNumberIndexRoute
}

const OwnerRepoPullNumberRouteChildren: OwnerRepoPullNumberRouteChildren = {
  OwnerRepoPullNumberFilesRoute: OwnerRepoPullNumberFilesRoute,
  OwnerRepoPullNumberIndexRoute: OwnerRepoPullNumberIndexRoute,
}

const OwnerRepoPullNumberRouteWithChildren =
  OwnerRepoPullNumberRoute._addFileChildren(OwnerRepoPullNumberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRepoPullsRoute: OwnerRepoPullsRoute,
  OwnerRepoPullNumberRoute: OwnerRepoPullNumberRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
